name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$(dig +short eu5.fusionsolar.huawei.com) intl.fusionsolar.huawei.com" | sudo tee -a /etc/hosts
      - run: |
          cat /etc/hosts
      - run: |
          ping -c 4 intl.fusionsolar.huawei.com