name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat /etc/resolv.conf
          cat /etc/systemd/resolved.conf
          resolvectl status
          systemd-resolve --status
          nslookup intl.fusionsolar.huawei.com 