name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat /etc/resolv.conf
      - run: |
          sudo echo -e "nameserver 1.1.1.1\n$(cat /etc/resolv.conf)" > /etc/resolv.conf
      - run: |
          cat /etc/resolv.conf
      - run: |
          nslookup intl.fusionsolar.huawei.com 