name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat /etc/resolv.conf
      - run: |
          cat /etc/systemd/resolved.conf
      - run: |
          sudo resolvectl dns eth0 1.1.1.1
      - run: |
          sudo resolvectl status
      - run: |
          nslookup intl.fusionsolar.huawei.com 