name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat /etc/resolv.conf
      - run: |
          cat /etc/systemd/resolved.conf
      - run: |
          resolvectl status
      - run: |
          systemd-resolve --status
      - run: |
          nslookup intl.fusionsolar.huawei.com 