name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat /etc/resolv.conf
      - run: |
          sudo sed -i '1s;^;nameserver 1.1.1.1\n;' /etc/resolv.conf
      - run: |
          cat /etc/resolv.conf
      - run: |
          nslookup intl.fusionsolar.huawei.com 