name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          nslookup huawei.com 
      - run: |
          nslookup fusionsolar.huawei.com 
      - run: |
          nslookup intl.fusionsolar.huawei.com
      - run: |
          nslookup region01eu5.fusionsolar.huawei.com