name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo sed -i -e '$a90.84.191.21 intl.fusionsolar.huawei.com' /etc/hosts
      - run: |
          cat /etc/hosts
      - run: |
          curl -vvv intl.fusionsolar.huawei.com