name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat /etc/resolv.conf
      - run: |
          cat /etc/systemd/resolved.conf
      - run: |
          cat /run/systemd/resolve/stub-resolv.conf
      - run: |
          sudo resolvectl dns eth0 1.1.1.1
      - run: |
          sudo systemctl daemon-reload
      - run: |
          sudo systemctl restart systemd-networkd
      - run: |
          sudo systemctl restart systemd-resolved
      - run: |
          sudo resolvectl flush-caches --no-pager
      - run: |
          sudo resolvectl status --no-pager
      - run: |
          nslookup intl.fusionsolar.huawei.com 