name: Test

on:
  push:
    branches:
      - main


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          sed -i -e '$a90.84.191.21 intl.fusionsolar.huawei.com ' /etc/hosts
      - run: |
          nslookup huawei.com 
      - run: |
          nslookup intl.fusionsolar.huawei.com
      - run: |
          nslookup region01eu5.fusionsolar.huawei.com